char1, char2 = input("Enter two space-separated characters: ").split()
highVal = max(char1, char2)
asciivalue1 = ord(char1)
asciivalue2 = ord(char2)
print("-------------------------------------")
print(f"The Character with the greater value is:  {highVal}")
print("-------------------------------------")

print("showing ASCII Values: ")
print (f"{char1} : {asciivalue1}")
print (f"{char2} : {asciivalue2}")